const VTK_TRIANGLE           = Int8( 5)
const VTK_QUAD               = Int8( 9)
const VTK_QUADRATIC_TRIANGLE = Int8(22)
const VTK_QUADRATIC_QUAD     = Int8(23)

const ABAQUS_CPS3 = VTK_TRIANGLE
const ABAQUS_CPS4 = VTK_QUAD
const ABAQUS_CPS6 = VTK_QUADRATIC_TRIANGLE
const ABAQUS_CPS8 = VTK_QUADRATIC_QUAD
