if (UM2_USE_CUDA)
  string(CONCAT UM2_CLANG_FLAGS 
    " -Wall"
    " -Wcast-align"
    " -Wcast-qual"
    " -Wconditional-uninitialized"
    " -Wconversion"
    " -Wdouble-promotion"
    " -Werror"
    " -Wextra"
    " -Wfloat-equal"
    " -Wheader-hygiene"
    " -Wimplicit-fallthrough"
    " -Wmissing-noreturn"
    " -Wnon-virtual-dtor"
    # " -Wold-style-cast"
    " -Woverriding-method-mismatch"
    " -Wrange-loop-analysis"
    #  " -Wreserved-identifier"
    " -Wshadow-all"
    " -Wshift-sign-overflow"
    " -Wtautological-type-limit-compare"
    " -Wtautological-unsigned-char-zero-compare"
    " -Wtautological-unsigned-enum-zero-compare"
    " -Wtautological-unsigned-zero-compare"
    " -Wtautological-value-range-compare"
    " -Wthread-safety"
    " -Wunaligned-access"
    " -Wundef"
    " -Wunneeded-member-function"
    " -Wunreachable-code-aggressive"
    " -Wunused"
    " -Wvector-conversion"
    " -Wvla"
    #  " -Wzero-as-null-pointer-constant"
    #  " -pedantic"
    " -fno-math-errno"
    )
else()
  string(CONCAT UM2_CLANG_FLAGS 
    " -Wall"
    " -Wcast-align"
    " -Wcast-qual"
    " -Wconditional-uninitialized"
    " -Wconversion"
    " -Wdouble-promotion"
    " -Werror"
    " -Wextra"
    " -Wfloat-equal"
    " -Wheader-hygiene"
    " -Wimplicit-fallthrough"
    " -Wmissing-noreturn"
    " -Wnon-virtual-dtor"
    " -Wold-style-cast"
    " -Woverriding-method-mismatch"
    " -Wrange-loop-analysis"
    " -Wreserved-identifier"
    " -Wshadow-all"
    " -Wshift-sign-overflow"
    " -Wtautological-type-limit-compare"
    " -Wtautological-unsigned-char-zero-compare"
    " -Wtautological-unsigned-enum-zero-compare"
    " -Wtautological-unsigned-zero-compare"
    " -Wtautological-value-range-compare"
    " -Wthread-safety"
    " -Wunaligned-access"
    " -Wundef"
    " -Wunneeded-member-function"
    " -Wunreachable-code-aggressive"
    " -Wunused"
    " -Wvector-conversion"
    " -Wvla"
    # " -Wzero-as-null-pointer-constant"
    " -pedantic"
    " -fno-math-errno"
    )
endif()
