if (UM2_USE_CUDA)
  string(CONCAT UM2_GNU_FLAGS 
    " -Wall"
    " -Wcast-align"
    " -Wcast-qual"
    " -Wconversion"
    " -Wdouble-promotion"
    " -Werror"
    " -Wextra"
    " -Wfloat-equal"
    " -Wimplicit-fallthrough"
    " -Wmissing-noreturn"
    " -Wnon-virtual-dtor"
    #  " -Wold-style-cast"
    " -Wshadow"
    " -Wundef"
    " -Wunused"
    " -Wvla"
    # " -Wzero-as-null-pointer-constant"
    # " -pedantic"
    " -fno-math-errno"
    )
else()
  string(CONCAT UM2_GNU_FLAGS 
    " -Wall"
    " -Wcast-align"
    " -Wcast-qual"
    " -Wconversion"
    " -Wdouble-promotion"
    " -Werror"
    " -Wextra"
    " -Wfloat-equal"
    " -Wimplicit-fallthrough"
    " -Wmissing-noreturn"
    " -Wnon-virtual-dtor"
    " -Wold-style-cast"
    " -Wshadow"
    " -Wsuggest-attribute=const"
    " -Wsuggest-attribute=pure"
    " -Wundef"
    " -Wunused"
    " -Wuseless-cast"
    " -Wvla"
    # " -Wzero-as-null-pointer-constant"
    " -pedantic"
    " -fno-math-errno"
    )
endif()
