set(Thrust_DIR "${PROJECT_SOURCE_DIR}/tpls/thrust/thrust/cmake")
find_package(Thrust REQUIRED CONFIG)        
if(UM2_ENABLE_CUDA)    
  thrust_create_target(Thrust)    
elseif(UM2_ENABLE_OPENMP)    
  thrust_create_target(Thrust DEVICE OMP)    
else()    
  thrust_create_target(Thrust DEVICE CPP)    
endif()
